# backend/app/api/manual.py

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import Optional
import io
import base64
import markdown
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from app.services.whisper_service import transcribe_audio

router = APIRouter(prefix="/manual", tags=["Manual Generation"])


class ManualRequest(BaseModel):
    issue_description: str
    solution: str
    format: str  # "pdf" or "markdown"
    session_id: Optional[str] = None


class ManualResponse(BaseModel):
    format: str
    content: str  # base64 encoded
    filename: str


@router.post("/generate", response_model=ManualResponse)
async def generate_manual(req: ManualRequest):
    """
    Generate a troubleshooting manual in PDF or Markdown format.
    Encodes the file content as base64 for easy frontend download.
    """
    try:
        if req.format == "markdown":
            # Generate markdown file
            content = f"""# Troubleshooting Manual

## Issue Description
{req.issue_description}

## Solution
{req.solution}

## Generated
This manual was automatically generated by HelpDesk AI.
"""
            encoded_content = base64.b64encode(content.encode()).decode()
            
            return ManualResponse(
                format="markdown",
                content=encoded_content,
                filename="troubleshooting-guide.md"
            )
            
        elif req.format == "pdf":
            # Generate PDF file
            buffer = io.BytesIO()
            c = canvas.Canvas(buffer, pagesize=letter)
            
            # Set up PDF content
            width, height = letter
            margin = 50
            y_position = height - margin
            
            # Title
            c.setFont("Helvetica-Bold", 18)
            c.drawString(margin, y_position, "Troubleshooting Manual")
            y_position -= 30
            
            # Issue Description
            c.setFont("Helvetica-Bold", 12)
            c.drawString(margin, y_position, "Issue Description:")
            y_position -= 20
            c.setFont("Helvetica", 10)
            
            # Wrap text for issue description
            words = req.issue_description.split()
            line = ""
            for word in words:
                if len(line + " " + word) < 80:
                    line += " " + word if line else word
                else:
                    c.drawString(margin, y_position, line)
                    y_position -= 15
                    line = word
            if line:
                c.drawString(margin, y_position, line)
                y_position -= 25
            
            # Solution
            c.setFont("Helvetica-Bold", 12)
            c.drawString(margin, y_position, "Solution:")
            y_position -= 20
            c.setFont("Helvetica", 10)
            
            # Wrap text for solution
            solution_lines = req.solution.split('\n')
            for line in solution_lines:
                if y_position < margin + 50:
                    c.showPage()
                    y_position = height - margin
                    
                words = line.split()
                wrapped_line = ""
                for word in words:
                    test_line = wrapped_line + " " + word if wrapped_line else word
                    c.setFont("Helvetica", 10)
                    if c.stringWidth(test_line) < width - 2 * margin:
                        wrapped_line = test_line
                    else:
                        c.drawString(margin, y_position, wrapped_line)
                        y_position -= 15
                        wrapped_line = word
                
                if wrapped_line:
                    c.drawString(margin, y_position, wrapped_line)
                    y_position -= 15
            
            # Footer
            y_position -= 20
            c.setFont("Helvetica-Oblique", 8)
            c.drawString(margin, y_position, "Generated by HelpDesk AI")
            
            c.save()
            buffer.seek(0)
            
            encoded_content = base64.b64encode(buffer.read()).decode()
            
            return ManualResponse(
                format="pdf",
                content=encoded_content,
                filename="troubleshooting-guide.pdf"
            )
            
        else:
            raise HTTPException(status_code=400, detail="Invalid format. Use 'pdf' or 'markdown'.")
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Manual generation failed: {str(e)}")
